Removing old files
Wealize/apminsight-site24x7-py pull request #1
Opened 2021-01-27 10:01 UTC by danitico

2021-01-27 16:04 UTC, danitico commented on apminsight_site24x7_py/instrumentation/dbapi2.py
> +            return original(*args, **kwargs)
The host info is already in the original connection object

2021-01-29 08:52 UTC, javaguirre commented
Just one thing, I'd keep the module name as it was `apminsight` but the repository name is fine. :-)

2021-01-29 08:52 UTC, javaguirre requested changes
Change package name back to `apminsight`

2021-01-29 11:53 UTC, javaguirre requested changes

2021-01-29 11:53 UTC, javaguirre commented on apminsight/contrib/django/apps.py
> +class apminsightConfig(AppConfig):
Apminsight?

2021-01-29 12:14 UTC, merged